#!/bin/bash

############################################################################################
# Allow AppRun or the AppImage to be symlinked to, e.g.,
# /usr/local/bin/inkview
# or to be called with ./Inkscape*.AppImage inkview
############################################################################################

if [ ! -z $APPIMAGE ] ; then
  BINARY_NAME=$(basename "$ARGV0")
else
  BINARY_NAME=$(basename "$0")
fi
if [ ! -z "$1" ] && [ -e "$APPDIR/usr/bin/$1" ] ; then
  MAIN="$APPDIR/usr/bin/$1" ; shift
elif [ -e "$APPDIR/usr/bin/$BINARY_NAME" ] ; then
  MAIN="$APPDIR/usr/bin/$BINARY_NAME"
else
  MAIN="$APPDIR/usr/bin/inkscape"
fi

############################################################################################
# Prefer to run the bundled executables (e.g., Python)
############################################################################################

export PATH="${APPDIR}/usr/bin:${PATH}"

############################################################################################
# Run experimental bundle that bundles everything if a private ld-linux-x86-64.so.2 is there
############################################################################################

PLATFORM=x86_64-linux-gnu

# Glib/Gtk environment
export GCONV_PATH="$APPDIR/usr/lib/$PLATFORM/gconv"
export FONTCONFIG_FILE="$APPDIR/etc/fonts/fonts.conf"
export GTK_EXE_PREFIX="$APPDIR/usr"
export GDK_PIXBUF_MODULEDIR=$(readlink -f "$APPDIR"/usr/lib/$PLATFORM/gdk-pixbuf-*/*/loaders/ )
export GDK_PIXBUF_MODULE_FILE=$(readlink -f "$APPDIR"/usr/lib/$PLATFORM/gdk-pixbuf-*/*/loaders.cache ) # Patched to contain no paths
export GI_TYPELIB_PATH="$APPDIR/usr/lib/$PLATFORM/girepository-1.0"

# For bundled themes
export XDG_DATA_DIRS="$APPDIR/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

# Shared library path
LIBRARY_PATH="$APPDIR/lib/$PLATFORM"
LIBRARY_PATH+=":$APPDIR/usr/lib/$PLATFORM"
LIBRARY_PATH+=":$APPDIR/usr/lib"
LIBRARY_PATH+=":$GDK_PIXBUF_MODULEDIR" # Otherwise getting "Unable to load image-loading module"

# Otherwise getting "Unable to load image-loading module" when opening extension manager
export LD_LIBRARY_PATH="$GDK_PIXBUF_MODULEDIR"


# Set inkscape data dir
export INKSCAPE_DATADIR="$APPDIR/usr/share"

exec "$APPDIR/lib/$PLATFORM/ld-linux-x86-64.so.2" --inhibit-cache --library-path "$LIBRARY_PATH" "$MAIN" "$@"
