name: Publish nuget

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare inkscape
      run: bash ./build.sh
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore
      working-directory: Inkscape
      run: dotnet restore
    - name: Build
      working-directory: Inkscape
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      working-directory: Inkscape
      run: dotnet pack --no-build --configuration Release
    - name: Publish
      working-directory: Inkscape
      run: dotnet nuget push Inkscape/bin/Release/Inkscape.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://www.nuget.org --skip-duplicate
