name: Publish nuget

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare inkscape
      run: bash ./build.sh
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Pack
      working-directory: Inkscape
      run: dotnet pack Inkscape --configuration Release
    - name: Check size
      working-directory: Inkscape
      run: ls -l Inkscape/bin/Release/Inkscape.*.nupkg
    - name: Publish
      working-directory: Inkscape
      run: dotnet nuget push Inkscape/bin/Release/Inkscape.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://www.nuget.org --skip-duplicate
